### ISSUE TITLE
Which TASM version should we use to build AEFdisk?

### ISSUE THREAD

**Issue by geraldo-netto** [nagydjol/aefdisk#1]
Dear @nagydjol ,

Some of our friends from freedos.org are interested in building AEFdisk but it seems TASM 4.1 didn't work [1]
Would you mind to tell us which version of TASM/Borland C compiler are you using?

[1] https://sourceforge.net/p/freedos/mailman/message/36498493/

Thank You Very Much/Kind Regards,
Geraldo Netto

**Comment by nagydjol** [comment]
Hi,

I used the tasm/tlink version from borlandc 3.1

Regards,

Daniel

**Comment by tkchia** [comment]
Hello @nagydjol ,

Thank you!  I have been trying to "port" `aefdisk` to build under the freely available Open Watcom toolchain; your information will be most helpful.
